//! The Tauri shell: the composition root that wires services, use cases and
//! dispatchers into the window, the command registry and the updater.

use crate::context::account::AccountService;
use crate::context::asset::{
    AssetPriceRepository, AssetService, PriceProvider, SqliteAssetPriceRepository,
};
use crate::context::currency::CurrencyService;
use crate::context::sync::{
    ChangeLogRepository, FirstPublish, FolderStore, FsFolderStore, Publisher,
    SqliteChangeLogRepository, SqliteChangeRecorder, SqliteSyncStateRepository, SyncRun,
    SyncService, SyncStateRepository,
};
use crate::core::event_bus::Event;
use crate::core::{create_specta_builder, Database, SideEffectEventBus, BACKEND};
use crate::shared::infrastructure::change_recorder::ChangeRecorder;
use crate::shared::infrastructure::container::AppContainer;
use crate::shared::infrastructure::scheduler::platform_scheduler;
use crate::use_cases::account_creation::AccountCreationUseCase;
use crate::use_cases::account_deletion::AccountDeletionUseCase;
use crate::use_cases::account_details::AccountDetailsUseCase;
use crate::use_cases::account_performance::AccountPerformanceUseCase;
use crate::use_cases::account_summary::AccountSummaryUseCase;
use crate::use_cases::archive_asset::ArchiveAssetUseCase;
use crate::use_cases::asset_price_fetch::dispatcher::Dispatcher as PriceFetchDispatcher;
use crate::use_cases::asset_price_fetch::{AssetPriceFetchUseCase, FetchGuard};
use crate::use_cases::asset_web_lookup::AssetWebLookupUseCase;
use crate::use_cases::capabilities::Capabilities;
use crate::use_cases::delete_asset::DeleteAssetUseCase;
use crate::use_cases::fee_generation::{FeeGenerationOrchestrator, LaunchSyncSurface};
use crate::use_cases::global_performance::GlobalPerformanceUseCase;
use crate::use_cases::holding_transaction::HoldingTransactionUseCase;
use crate::use_cases::portfolio_sync::{
    PortfolioSyncDependencies, PortfolioSyncOrchestrator, ServicePortfolioSnapshot,
    ServiceRankStamper,
};
use crate::use_cases::price_freshness::PriceFreshnessUseCase;
use crate::use_cases::price_history_backfill::PriceHistoryBackfillUseCase;
use crate::use_cases::rate_history_backfill::RateHistoryBackfillUseCase;
use crate::use_cases::rate_refresh::RateRefreshUseCase;
use crate::use_cases::scheduled_fetch::orchestrator::drop_schedule_without_provider;
use crate::use_cases::scheduled_fetch::{
    ScheduledFetchOrchestrator, SqliteScheduledFetchRepository,
};
use crate::use_cases::shared::price_fetch_log::{
    PriceFetchLogRepository, SqlitePriceFetchLogRepository,
};
use crate::use_cases::update_checker::UpdateState;
use crate::{extensions, shared, AppState};
use anyhow::Context;
use std::{fs, path::PathBuf, sync::Arc};
use tauri::{Emitter, Manager};
use tauri_specta::Event as _;

/// Update lifecycle state — managed separately so it is accessible without a DB.
pub(crate) type ManagedUpdateState = Arc<UpdateState>;

/// Entry point for the Tauri application.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_specta_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n/* eslint-disable */\n// Generated by Specta - do not edit manually\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export typescript bindings");

    let invoke_handler = builder.invoke_handler();

    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(
            tauri_plugin_window_state::Builder::default()
                .with_state_flags(
                    tauri_plugin_window_state::StateFlags::SIZE
                        | tauri_plugin_window_state::StateFlags::MAXIMIZED
                        | tauri_plugin_window_state::StateFlags::VISIBLE
                        | tauri_plugin_window_state::StateFlags::DECORATIONS
                        | tauri_plugin_window_state::StateFlags::FULLSCREEN,
                )
                .build(),
        )
        .plugin(tauri_plugin_dialog::init())
        .setup(move |app| {
            let app_handle = app.handle().clone();

            builder.mount_events(&app_handle);

            let dirs = create_app_dirs(&app_handle)?;
            crate::initialize_tracing(&dirs.log_dir)?;
            tracing::info!(target: BACKEND, "Initializing application backend");
            tracing::trace!(target: BACKEND, data_dir = ?dirs.local_data_dir, log_dir = ?dirs.log_dir, "Application directories");

            // Manage update state before DB init so it is available even on migration failure (R10, R18)
            app_handle.manage(Arc::new(UpdateState::new()) as ManagedUpdateState);

            // The update channel and the external data sources come from `extensions.rs`
            // (ADR-020). The HTTP clients are built here, outside the keep-running async
            // block, so a TLS-init failure surfaces as a graceful setup error rather than
            // a panic.
            app_handle.manage(extensions::update_channel());
            let providers = extensions::providers()?;

            tauri::async_runtime::block_on(async move {
                // R18 — emit migration error and keep app running so frontend can show error screen
                let db = match Database::new(dirs.local_data_dir).await {
                    Ok(db) => Arc::new(db),
                    Err(e) => {
                        tracing::error!(target: BACKEND, error = %e, "Database initialization failed (R18)");
                        let _ = app_handle.emit("db:migration_error", e.to_string());
                        return;
                    }
                };
                tracing::info!(target: BACKEND, "Database initialized successfully");

                let event_bus = Arc::new(SideEffectEventBus::new());

                // Spawn event forwarder
                let mut rx = event_bus.subscribe();
                let forwarder_handle = app_handle.clone();
                tauri::async_runtime::spawn(async move {
                    loop {
                        if rx.changed().await.is_err() {
                            break;
                        }
                        let event = rx.borrow().clone();
                        let _ = Event::emit(&event, &forwarder_handle);
                    }
                });

                // ----- multi-device sync (SYN) -----
                let sync_state_repo: Arc<dyn SyncStateRepository> =
                    Arc::new(SqliteSyncStateRepository::new(db.pool.clone()));
                let sync_folder_store: Arc<dyn FolderStore> =
                    Arc::new(FsFolderStore::new(PathBuf::new()));
                let sync_change_log: Arc<dyn ChangeLogRepository> =
                    Arc::new(SqliteChangeLogRepository::new(db.pool.clone()));
                let change_recorder = Arc::new(SqliteChangeRecorder::new(db.pool.clone()));
                let sync_run = Arc::new(SyncRun::new(
                    Arc::clone(&sync_change_log),
                    Arc::clone(&sync_state_repo),
                    Arc::clone(&sync_folder_store),
                    Arc::clone(&change_recorder) as Arc<dyn ChangeRecorder>,
                ));
                let sync_service = Arc::new(
                    SyncService::new(Arc::clone(&sync_state_repo), Arc::clone(&sync_folder_store))
                        .with_run(Arc::clone(&sync_run))
                        .with_event_bus(Arc::clone(&event_bus)),
                );
                let price_provider = providers.price;
                let AppContainer {
                    account_service,
                    asset_service,
                    currency_service,
                } = AppContainer::build(
                    db.pool.clone(),
                    Some(providers.rate),
                    Some(providers.rate_history),
                    Some(Arc::clone(&event_bus)),
                    Arc::clone(&change_recorder) as Arc<dyn ChangeRecorder>,
                );

                let account_details_uc = AccountDetailsUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                    Arc::clone(&currency_service),
                );

                let account_summary_uc = AccountSummaryUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                    Arc::clone(&currency_service),
                );

                let account_performance_uc = AccountPerformanceUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                    Arc::clone(&currency_service),
                );

                let global_performance_uc = GlobalPerformanceUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                    Arc::clone(&currency_service),
                );

                let archive_asset_uc = ArchiveAssetUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                );

                let delete_asset_uc = DeleteAssetUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                );

                let account_deletion_uc =
                    AccountDeletionUseCase::new(account_service.clone());

                let account_creation_uc = AccountCreationUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                );

                let holding_transaction_uc = HoldingTransactionUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                );

                // The first-device publish reads and ranks the whole portfolio through the
                // owning contexts' services (B24); a join and a run write through them.
                let first_publish = Arc::new(FirstPublish::new(
                    sync_change_log,
                    Arc::clone(&sync_state_repo),
                    Arc::clone(&sync_folder_store),
                    Arc::new(ServiceRankStamper::new(
                        account_service.clone(),
                        asset_service.clone(),
                        Arc::clone(&currency_service),
                    )),
                    Arc::new(ServicePortfolioSnapshot::new(
                        account_service.clone(),
                        asset_service.clone(),
                        Arc::clone(&currency_service),
                    )),
                ));
                let portfolio_sync_uc =
                    Arc::new(PortfolioSyncOrchestrator::new(PortfolioSyncDependencies {
                        account_service: account_service.clone(),
                        asset_service: asset_service.clone(),
                        currency_service: Arc::clone(&currency_service),
                        sync_service: Arc::clone(&sync_service),
                        first_publish,
                        sync_run,
                        state_repo: sync_state_repo,
                        folder_store: sync_folder_store,
                    }));
                // SYN-060/067 — every recorded change restarts the settling window; a settled
                // burst runs one automatic sync.
                let automatic_sync = Arc::clone(&portfolio_sync_uc);
                change_recorder.attach_recorded_change_hook(
                    Arc::new(Publisher::new()).recorded_change_hook(move || {
                        let portfolio_sync = Arc::clone(&automatic_sync);
                        async move { portfolio_sync.sync_after_changes().await }
                    }),
                );

                // FEE-040 — lazy catch-up generation across all active fee schedules,
                // invoked by the frontend on app startup; SYN-060 — one sync runs first.
                let fee_generation_uc = FeeGenerationOrchestrator::new(account_service.clone())
                    .with_launch_sync(Arc::new(LaunchSync(Arc::clone(&portfolio_sync_uc))));

                app_handle.manage(account_details_uc);
                app_handle.manage(account_summary_uc);
                app_handle.manage(account_performance_uc);
                app_handle.manage(global_performance_uc);
                app_handle.manage(archive_asset_uc);
                app_handle.manage(delete_asset_uc);
                app_handle.manage(account_deletion_uc);
                app_handle.manage(account_creation_uc);
                app_handle.manage(holding_transaction_uc);
                app_handle.manage(fee_generation_uc);

                app_handle.manage(AssetWebLookupUseCase::new(providers.asset_lookup));

                // ----- asset price fetch (the build's External provider, ADR-020) -----
                // MKT-201 — this installation's fetch log, written by both fetch paths.
                let price_fetch_log: Arc<dyn PriceFetchLogRepository> =
                    Arc::new(SqlitePriceFetchLogRepository::new(db.pool.clone()));
                // MKT-200/201 — the header's price item. It reads prices already
                // recorded and this device's fetch log, so it is built whether or not
                // anything can fetch.
                app_handle.manage(Arc::new(PriceFreshnessUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                    Arc::clone(&price_fetch_log),
                )));

                // MKT-211, UPD-030 — what the interface is told about this build.
                app_handle.manage(Capabilities::of_build(
                    price_provider.is_some(),
                    extensions::distribution_channel(),
                ));
                // MKT-210, SPF-070 — what fetches prices.
                manage_price_fetching(
                    &app_handle,
                    price_provider,
                    PriceFetchingParts {
                        pool: db.pool.clone(),
                        account_service: account_service.clone(),
                        asset_service: asset_service.clone(),
                        currency_service: Arc::clone(&currency_service),
                        event_bus: Arc::clone(&event_bus),
                        price_fetch_log,
                    },
                );

                // FXR-110 — "Update rates" in the Currency Rates view.
                app_handle.manage(Arc::new(RateHistoryBackfillUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                    Arc::clone(&currency_service),
                )));
                // FXR-075 — the launch rate refresh, in every build.
                app_handle.manage(Arc::new(RateRefreshUseCase::new(
                    account_service.clone(),
                    asset_service.clone(),
                    Arc::clone(&currency_service),
                )));

                app_handle.manage(portfolio_sync_uc);
                app_handle.manage(sync_service);

                app_handle.manage(Arc::clone(&currency_service));

                app_handle.manage(AppState {
                    db,
                    event_bus,
                    asset_service,
                    account_service,
                });

                tracing::info!(target: BACKEND, "Application backend initialized successfully");
            });

            Ok(())
        })
        .invoke_handler(invoke_handler)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

/// What the price-fetching paths of the composition root are built from.
struct PriceFetchingParts {
    pool: sqlx::SqlitePool,
    account_service: Arc<AccountService>,
    asset_service: Arc<AssetService>,
    currency_service: Arc<CurrencyService>,
    event_bus: Arc<SideEffectEventBus>,
    price_fetch_log: Arc<dyn PriceFetchLogRepository>,
}

/// MKT-210, SPF-070 — the three paths that fetch prices exist only with an External
/// provider. Without one no fetching use case is managed, so no command reaches a
/// half-built one, and a scheduled fetch a build with a provider registered is taken away.
fn manage_price_fetching<R: tauri::Runtime>(
    app_handle: &tauri::AppHandle<R>,
    price_provider: Option<Arc<dyn PriceProvider>>,
    parts: PriceFetchingParts,
) {
    let Some(price_provider) = price_provider else {
        tauri::async_runtime::spawn(async {
            drop_schedule_without_provider(platform_scheduler().as_ref()).await;
        });
        return;
    };
    let PriceFetchingParts {
        pool,
        account_service,
        asset_service,
        currency_service,
        event_bus,
        price_fetch_log,
    } = parts;

    let fetch_guard = Arc::new(FetchGuard::new());
    let price_repo_for_fetch: Arc<dyn AssetPriceRepository> =
        Arc::new(SqliteAssetPriceRepository::new(pool.clone()));
    let dispatcher = Arc::new(
        PriceFetchDispatcher::new(
            Arc::clone(&price_provider),
            price_repo_for_fetch,
            Arc::clone(&event_bus),
            Arc::new(|| chrono::Local::now().date_naive()),
        )
        .with_fetch_log(
            Arc::clone(&price_fetch_log),
            Arc::new(|| chrono::Local::now().naive_local()),
        ),
    );
    app_handle.manage(Arc::new(AssetPriceFetchUseCase::new(
        account_service.clone(),
        asset_service.clone(),
        Arc::clone(&fetch_guard),
        Arc::clone(&dispatcher),
        Arc::clone(&currency_service),
    )));

    // ----- scheduled daily price download (SPF) -----
    let scheduled_fetch_orchestrator = Arc::new(
        ScheduledFetchOrchestrator::new(
            account_service.clone(),
            asset_service.clone(),
            Arc::clone(&price_provider),
            Arc::clone(&currency_service),
            Arc::new(SqliteScheduledFetchRepository::new(pool)),
            platform_scheduler(),
            Arc::new(|| chrono::Local::now().naive_local()),
        )
        .with_fetch_log(price_fetch_log),
    );
    // SPF-015 — verify/repair the OS schedule against the stored configuration on every
    // app start; failures are logged, never surfaced.
    let self_heal_orchestrator = Arc::clone(&scheduled_fetch_orchestrator);
    tauri::async_runtime::spawn(async move {
        self_heal_orchestrator.self_heal().await;
    });
    app_handle.manage(scheduled_fetch_orchestrator);

    // MKT-190 — price history backfill of one holding.
    app_handle.manage(Arc::new(PriceHistoryBackfillUseCase::new(
        account_service,
        asset_service,
        price_provider,
        Arc::new(|| chrono::Local::now().date_naive()),
    )));
}

/// SYN-060/D9 — the launch sync the fee-generation use case runs before generating: one
/// full run through the portfolio-sync use case, composed here so neither use case imports
/// the other (B18). Never fails outward — sync disabled, paused, or failing is logged.
struct LaunchSync(Arc<PortfolioSyncOrchestrator>);

#[async_trait::async_trait]
impl LaunchSyncSurface for LaunchSync {
    async fn run_launch_sync(&self) {
        if let Err(error) = self.0.sync_now().await {
            tracing::info!(target: BACKEND, err = %error, "launch sync skipped");
        }
    }
}

/// Application directory paths resolved at startup.
#[derive(Debug, Clone)]
struct AppDirectories {
    /// Path to the app-scoped local data directory (database location).
    local_data_dir: PathBuf,
    /// Path to the app-scoped log directory (log file location).
    log_dir: PathBuf,
}

fn create_app_dirs(app: &tauri::AppHandle) -> anyhow::Result<AppDirectories> {
    use shared::infrastructure::{app_directories, e2e_run};

    // A debug build keeps its data and logs in development folders of its own; an E2E
    // run injects an isolated data folder so each run starts from a clean database.
    // Only a release build opens the installed application's folders.
    let (local_data_dir, log_dir) = if cfg!(debug_assertions) {
        app_directories::development_directories(e2e_run::e2e_data_dir())
            .with_context(|| "Failed to get the development directories")?
    } else {
        let path_resolver = app.path();
        let local_data_dir = path_resolver
            .app_local_data_dir()
            .with_context(|| "Failed to get app local data directory")?;
        let log_dir = path_resolver
            .app_log_dir()
            .with_context(|| "Failed to get app log directory")?;
        (local_data_dir, log_dir)
    };
    fs::create_dir_all(&local_data_dir).with_context(|| "Failed to create data directory")?;
    fs::create_dir_all(&log_dir).with_context(|| "Failed to create log directory")?;

    Ok(AppDirectories {
        local_data_dir,
        log_dir,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::context::asset::MockPriceProvider;

    async fn parts() -> PriceFetchingParts {
        let pool = sqlx::sqlite::SqlitePoolOptions::new()
            .max_connections(1)
            .connect("sqlite::memory:")
            .await
            .expect("pool");
        sqlx::migrate!("./migrations")
            .run(&pool)
            .await
            .expect("migrations");
        let recorder: Arc<dyn ChangeRecorder> = Arc::new(SqliteChangeRecorder::new(pool.clone()));
        let AppContainer {
            account_service,
            asset_service,
            currency_service,
        } = AppContainer::build(pool.clone(), None, None, None, recorder);
        PriceFetchingParts {
            price_fetch_log: Arc::new(SqlitePriceFetchLogRepository::new(pool.clone())),
            pool,
            account_service,
            asset_service,
            currency_service,
            event_bus: Arc::new(SideEffectEventBus::new()),
        }
    }

    // MKT-210 — without an External provider no fetching use case exists, so no command
    // can reach one.
    #[tokio::test]
    async fn a_build_without_an_external_provider_manages_no_fetching_use_case() {
        let app = tauri::test::mock_app();

        manage_price_fetching(app.handle(), None, parts().await);

        assert!(app.try_state::<Arc<AssetPriceFetchUseCase>>().is_none());
        assert!(app.try_state::<Arc<ScheduledFetchOrchestrator>>().is_none());
        assert!(app
            .try_state::<Arc<PriceHistoryBackfillUseCase>>()
            .is_none());
    }

    // MKT-210 — with one, the three fetching paths exist.
    #[tokio::test]
    async fn a_build_with_an_external_provider_manages_the_three_fetching_use_cases() {
        let app = tauri::test::mock_app();

        manage_price_fetching(
            app.handle(),
            Some(Arc::new(MockPriceProvider::new())),
            parts().await,
        );

        assert!(app.try_state::<Arc<AssetPriceFetchUseCase>>().is_some());
        assert!(app.try_state::<Arc<ScheduledFetchOrchestrator>>().is_some());
        assert!(app
            .try_state::<Arc<PriceHistoryBackfillUseCase>>()
            .is_some());
    }
}
